export { default as animatedCoffeeShop } from './animated-coffee-shop.gif'
export { default as defaultAvatar } from './default-avt.png'
export { default as heroBanner } from './hero-banner.svg'
export { default as iceCube } from './ice.png'
export { default as leaf } from './leaf.png'
export { default as ngooCfText } from './ngoo-cf-text.svg'
export { default as notifyBg } from './notify-bg.svg'
export { default as summerBeach } from './summer-beach.webp'
